[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml" 